{
  "hash": "152e793d06a8ab759bb88ff4e29784a3",
  "result": {
    "markdown": "---\ntitle: \"Getting to know Stan - SWOSC\"\nauthor: \"Ben Stockton\"\ndate: \"2023-11-16\"\nresults: hold\nbibliography: swosc-stan.bib\ncategories: [bayesian inference]\nfreeze: true\n---\n\n\n## Installation\n\nTo get started, we'll head over to Stan's [documentation](https://mc-stan.org/) to see how to get set up in R. For this presentation, I'll use the CmdStan toolchain that's implemented in R by the `cmdstanr` [package](https://mc-stan.org/cmdstanr/) [@gabry2023]. There are also Python, command line, Matlab, Julia, and Stata interfaces to Stan and a Python interface for cmdstan called [CmdStanPy](https://github.com/stan-dev/cmdstanpy) [@cmdstanp].\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"cmdstanr\", repos = c(\"https://mc-stan.org/r-packages/\", getOption(\"repos\")))\nlibrary(cmdstanr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is cmdstanr version 0.6.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n- CmdStan path: /Users/lcgodoy/.cmdstan/cmdstan-2.33.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n- CmdStan version: 2.33.1\n```\n:::\n\n```{.r .cell-code}\n# cmdstanr::install_cmdstan()\ncmdstanr::cmdstan_version()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2.33.1\"\n```\n:::\n\n```{.r .cell-code}\ncmdstanr::cmdstan_path()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"/Users/lcgodoy/.cmdstan/cmdstan-2.33.1\"\n```\n:::\n\n```{.r .cell-code}\ncmdstanr::check_cmdstan_toolchain()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe C++ toolchain required for CmdStan is setup properly!\n```\n:::\n:::\n\n\n## A Very Brief Introduction to Bayesian Data Analysis\n\nThe broadest conceptual overview of Bayesian data analysis is that this methodology allows us to incorporate prior knowledge about the model/data into our analysis which is based on a posterior distribution that is derived from the prior and likelihood. Bayesian inference treats the parameters of the model as random variables whose distribution we are interested in either deriving analytically or approximating through computation. This is a key distinction from frequentist methods taught in math stat and applied stat where parameters are fixed values and their estimators are functions of a random sample and the sampling distribution of the estimator is used for inference.\n\n::: callout-important\n## Bayes Rule\n\nA quick reminder of Bayes Rule.\n\nLet $\\theta$ be a random variable with (prior) distribution $p(\\theta)$, $Y$ be a random variable that depends on $\\theta$ with conditional distribution or likelihood $p(y | \\theta)$. Then their joint distribution is $p(y, \\theta) = p(y|\\theta) p(\\theta)$.\n\nBayes rule lets us flip the conditioning from the likelihood to get $p(\\theta | y)$\n\n$$\np(\\theta | y) = \\frac{p(y, \\theta)}{p(y)} = \\frac{p(y|\\theta) p(\\theta)}{\\int p(y, \\theta) d\\theta} \\approx p(y|\\theta) p(\\theta)\n$$\n:::\n\nTo be a little more specific, we have three central components to the model. For ease of exposition, let's consider the simple regression model $E(Y_i | X_i = x_i, \\boldsymbol{\\beta}, \\sigma^2) = \\beta_0 + \\beta_1 X_i$ and $Var(Y_i | X_i = x_i, \\boldsymbol{\\beta}, \\sigma^2) = \\sigma^2$ where we have $i = 1,\\dots,N$ observations of $(Y_i, X_i)'$ from Ch. 14 of Bayesian Data Analysis [@gelman2013bayesian, p. 354-358]. From here on I will suppress conditioning on the observed predictor $X_i = x_i$ since we are considering the design matrix $X = (1_N, \\mathbf{x})$ to be fixed and known where $\\mathbf{x} = (x_1,\\dots, x_N)'$.\n\n1.  **The Prior:** a distribution for the parameters that doesn't depend on the data.\n    1.  For the regression model, we have three parameters $\\beta_0, \\beta_1, \\sigma^2$. We assign a probability distribution $p(\\beta_0, \\beta_1, \\sigma^2) \\equiv p(\\boldsymbol{\\beta}, \\sigma^2)$ to these parameters. One common way to do this are a non-informative prior so that the prior is uniform $p(\\boldsymbol{\\beta}, \\log\\sigma) = 1 \\equiv p(\\boldsymbol{\\beta}, \\sigma^2) \\propto \\sigma^{-2}$.\n2.  **The (Data) Likelihood:** a model for the data that depends on the parameters.\n    1.  For the regression, we have the model $Y_i | \\boldsymbol{\\beta}, \\sigma^2 \\sim N(\\beta_0 + \\beta_1 x_i, \\sigma^2) \\equiv p(y_i | \\boldsymbol{\\beta}, \\sigma^2) = \\phi(y_i | \\beta_0 + \\beta_1 x_i, \\sigma^2).$ Note that we are conditioning on the parameters.\n    2.  In vector notation, this is $\\mathbf{Y} | \\boldsymbol{\\beta}, \\sigma^2 \\sim N_N(X\\boldsymbol{\\beta}, \\sigma^2 I_N).$\n3.  **The Posterior:** a distribution that uses Bayes rule to define distribution of the parameters given the data.\n    1.  For the regression model we are able to find an analytic solution to the posterior when we have a non-informative prior $p(\\boldsymbol{\\beta}, \\sigma^2) \\propto \\sigma^{-2}$, or for a conjugate prior $p(\\boldsymbol{\\beta} | \\sigma^2) = \\phi(\\beta_0) \\phi(\\beta_1)$ and $p(\\sigma^2) = InvGamma(\\frac{\\nu_0}{2}, \\frac{1}{2} \\nu_0 s_0^2).$\n    2.  The joint posterior for the non-informative prior is expressed as\n\n\n```{=tex}\n\\begin{align*}\n    p(\\boldsymbol{\\beta}, \\sigma^2 | \\mathbf{y}) &= p(\\boldsymbol{\\beta} | \\sigma^2, \\mathbf{y}) \\times p(\\sigma^2 | \\mathbf{y}) \\\\\n        &= N_2(\\boldsymbol{\\beta} | \\hat{\\boldsymbol{\\beta}}, \\sigma^2 (X'X)^{-1}) \\times Inv-\\chi^2 (\\sigma^2 | N-2, s^2) \\\\\n    \\hat{\\boldsymbol{\\beta}} &= (X'X)^{-1} X'\\mathbf{y} \\\\\n    s^2 &= \\frac{1}{N-2} (\\mathbf{y} - X\\hat{\\boldsymbol{\\beta}})' (\\mathbf{y} - X\\hat{\\boldsymbol{\\beta}})   \n\\end{align*}\n```\n\n## Some examples in Stan\n\nWe'll continue with the single predictor regression model to model NCAA Women's Basketball team's total wins by their 3 point field goal percentage from the 2022-2023 season. Data collected from [NCAA](https://stats.ncaa.org/rankings?sport_code=WBB&division=2).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nncaaw <- readr::read_csv(file = \"Data/NCAAW-freethrows-threes-2022-2023.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 350 Columns: 11\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Team, WL\ndbl (9): G, FT, FTA, FTpct, FG3, FG3A, FG3pct, W, L\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n\nIn the 2022-2023 season there were $N = 350$ teams. The relationship between their wins and three point percentage is displayed in @fig-scatter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ncaaw, aes(FG3pct, W)) +\n    geom_point() +\n    geom_smooth(method = \"lm\", se = FALSE) +\n    labs(title = \"2022-23 NCAAW Wins by 3pt%\", \n         subtitle = paste0(\"r = \", round(cor(ncaaw$W, ncaaw$FG3pct), 3)),\n         x = \"3pt%\",\n         y = \"Wins\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![Scatter plot of the Total Wins by 3 pt Field Goal %. The OLS regression line is super-imposed in blue.](intro_to_stan_files/figure-html/fig-scatter-1.png){#fig-scatter width=672}\n:::\n:::\n\n\nAs a baseline, we'll find the maximum likelihood estimates for the regression parameters and variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ml <- lm(W ~ FG3pct, data = ncaaw)\n\ncoef(fit_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      FG3pct \n  -14.94468     1.00929 \n```\n:::\n\n```{.r .cell-code}\nsmry_ml <- summary(fit_ml)\nsmry_ml$sigma^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 34.90616\n```\n:::\n:::\n\n\n### Non-informative Prior Regression Model\n\nFirst we write the Stan code in a separate file. See the [Stan User's Guide Part 1.1](https://mc-stan.org/docs/stan-users-guide/linear-regression.html#vectorization.section) for programming this model without the analytic posteriors.\n\n``` {.stan filename=\"non-informative-regression.stan\"}\n// The input data is two vectors 'y' and 'X' of length 'N'.\ndata {\n  int<lower=0> N;\n  vector[N] y;\n  vector[N] x;\n}\n\ntransformed data {\n    matrix[N, 2] X_c = append_col(rep_vector(1, N), x);\n    matrix[2,2] XtX_inv = inverse(X_c' * X_c);\n\n    vector[2] beta_hat = XtX_inv * X_c' * y;\n    vector[N] y_hat = X_C * beta_hat;\n    \n    real<lower=0> s_2 = 1 / (N - 2) * (y - y_hat)' * (y - y_hat);\n}\n\n// The parameters accepted by the model. Our model\n// accepts two parameters 'beta' and 'sigma'.\nparameters {\n  vector beta;\n  real<lower=0> sigma; // Note that this is the variance\n}\n\n// The model to be estimated. We model the output\n// 'y' ~ N(x beta, sigma) by specifying the analytic\n// posterior defined above.\nmodel {\n  beta ~ multi_normal(beta_hat, sigma^2 * XtX_inv);\n  \n  sigma^2 ~ scaled_inv_chi_square(N-2, sqrt(s_2));\n}\n\ngenerated quantities {\n    vector[N] y_ppd;\n    \n    for (i in 1:N) {\n        y_ppd[i] = normal_rng(X_c[i,] * beta, sigma);\n    }\n}\n```\n\nNext we fit the model using `cmdstanr`. In this case, I will use 1000 warmup iterations, 1000 sampling iterations, with no thinning (thinning includes only every $k$th draw), and will refresh the print screen to see progress every 500 iterations. We can run several chains to see if where the chains start dictates any part of the posterior shape or location, and chains can be run in parallel to get more draws \\<=\\> better posterior approximation more quickly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_list <- list(\n    N = nrow(ncaaw),\n    y = ncaaw$W,\n    x = ncaaw$FG3pct\n)\n\nfile <- file.path(\"non-informative-regression.stan\")\nnon_inf_model <- cmdstan_model(file)\n\nfit1 <- non_inf_model$sample(\n    data = data_list,\n    iter_warmup = 1000,\n    iter_sampling = 1000,\n    thin = 1,\n    refresh = 500,\n    chains = 2,\n    show_messages = TRUE,\n    show_exceptions = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRunning MCMC with 2 sequential chains...\n\nChain 1 Iteration:    1 / 2000 [  0%]  (Warmup) \nChain 1 Iteration:  500 / 2000 [ 25%]  (Warmup) \nChain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup) \nChain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling) \nChain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling) \nChain 1 Iteration: 2000 / 2000 [100%]  (Sampling) \nChain 1 finished in 0.2 seconds.\nChain 2 Iteration:    1 / 2000 [  0%]  (Warmup) \nChain 2 Iteration:  500 / 2000 [ 25%]  (Warmup) \nChain 2 Iteration: 1000 / 2000 [ 50%]  (Warmup) \nChain 2 Iteration: 1001 / 2000 [ 50%]  (Sampling) \nChain 2 Iteration: 1500 / 2000 [ 75%]  (Sampling) \nChain 2 Iteration: 2000 / 2000 [100%]  (Sampling) \nChain 2 finished in 0.2 seconds.\n\nBoth chains finished successfully.\nMean chain execution time: 0.2 seconds.\nTotal execution time: 0.6 seconds.\n```\n:::\n:::\n\n\nNext we'll check diagnostics for the sampler. First, we will look at the numeric diagnostic output from the method `$diagnostic_summary()` which reports if any transitions were divergent, if maximum tree depth was reached, and EBFMI. For this model and data set we don't see any issues in these summaries.\n\nNext, we check the traceplots in @fig-traceplots-non-info-1. The MCMC draws can be collected from the `fit` object using the `$draws()` method. These plots display the sampled values for each parameter in a line plot. We are looking for a horizontal fuzzy bar. Then we can also look at density plots in @fig-traceplots-non-info-2 which will tell us if the chains reached reasonably similar densities. On both counts, we are in good shape. The plots are created using the `bayesplot` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit1$diagnostic_summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$num_divergent\n[1] 0 0\n\n$num_max_treedepth\n[1] 0 0\n\n$ebfmi\n[1] 1.001863 1.101070\n```\n:::\n:::\n\n::: {#fig-traceplots-non-info .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nlibrary(bayesplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is bayesplot version 1.10.0\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n- Online documentation and vignettes at mc-stan.org/bayesplot\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n- bayesplot theme set to bayesplot::theme_default()\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n   * Does _not_ affect other ggplot2 plots\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n   * See ?bayesplot_theme_set for details on theme setting\n```\n:::\n\n```{.r .cell-code}\nmcmc_trace(fit1$draws(variables = c(\"beta\", \"sigma\")))\n\nmcmc_dens_overlay(fit1$draws(variables = c(\"beta\", \"sigma\")))\n```\n\n::: {.cell-output-display}\n![Traceplots for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-traceplots-non-info-1.png){#fig-traceplots-non-info-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Approximate posterior densities for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-traceplots-non-info-2.png){#fig-traceplots-non-info-2 width=672}\n:::\n\nDiagnostic plots for the posterior samples. Plots were made using the `bayesplot` package.\n:::\n\n\nFinally, after checking that the MCMC chains and diagnostics look satisfactory, we can continue to inference. The summary statistics for the parameters are displayed in @tbl-non-info-inf. This are generated by default with the `$summary()` method. The statistics include the posterior mean (`mean`), median (`median`), standard deviation (`sd`), mean absolute deviation (`mad`), and lower (`q5`) and upper bounds (`q95`) for a 90% credible interval. The statistics `rhat`, `ess_bulk`, and `ess_tail` are additional diagnostic measures that indicate how well the chains are sampling the posterior and how many effective draws we have made. Ideally `rhat` is very near 1, even 1.01 can be a significant problem. The effective sample sizes should be large/near the number of sampling iterations.\n\n\n::: {#tbl-non-info-inf .cell tbl-cap='Summary statistics for the posterior samples for $\\beta$ and $\\sigma$.'}\n\n```{.r .cell-code}\nfit1$summary(variables = c(\"beta\", \"sigma\")) |> \n    kableExtra::kbl(booktabs = TRUE, format = \"html\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> variable </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> median </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> mad </th>\n   <th style=\"text-align:right;\"> q5 </th>\n   <th style=\"text-align:right;\"> q95 </th>\n   <th style=\"text-align:right;\"> rhat </th>\n   <th style=\"text-align:right;\"> ess_bulk </th>\n   <th style=\"text-align:right;\"> ess_tail </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> beta[1] </td>\n   <td style=\"text-align:right;\"> -14.917746 </td>\n   <td style=\"text-align:right;\"> -14.86870 </td>\n   <td style=\"text-align:right;\"> 2.9209916 </td>\n   <td style=\"text-align:right;\"> 2.9490397 </td>\n   <td style=\"text-align:right;\"> -19.5959800 </td>\n   <td style=\"text-align:right;\"> -10.098950 </td>\n   <td style=\"text-align:right;\"> 1.003222 </td>\n   <td style=\"text-align:right;\"> 593.7010 </td>\n   <td style=\"text-align:right;\"> 702.8783 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> beta[2] </td>\n   <td style=\"text-align:right;\"> 1.008556 </td>\n   <td style=\"text-align:right;\"> 1.00855 </td>\n   <td style=\"text-align:right;\"> 0.0936737 </td>\n   <td style=\"text-align:right;\"> 0.0947700 </td>\n   <td style=\"text-align:right;\"> 0.8561433 </td>\n   <td style=\"text-align:right;\"> 1.160748 </td>\n   <td style=\"text-align:right;\"> 1.002490 </td>\n   <td style=\"text-align:right;\"> 592.1065 </td>\n   <td style=\"text-align:right;\"> 740.6761 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> sigma </td>\n   <td style=\"text-align:right;\"> 5.928982 </td>\n   <td style=\"text-align:right;\"> 5.92578 </td>\n   <td style=\"text-align:right;\"> 0.2305663 </td>\n   <td style=\"text-align:right;\"> 0.2281647 </td>\n   <td style=\"text-align:right;\"> 5.5632945 </td>\n   <td style=\"text-align:right;\"> 6.307927 </td>\n   <td style=\"text-align:right;\"> 1.000307 </td>\n   <td style=\"text-align:right;\"> 759.7555 </td>\n   <td style=\"text-align:right;\"> 560.6763 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nWe can also check graphical summaries of this same information such as interval plots for each parameter's credible intervals or density/area plots. In @fig-non-info-ci-1 we have the 50% (thick bar) and 95% (thin bar) credible intervals with the posterior mean displayed as a point. The densities are plotted in ridgelines in @fig-non-info-ci-2 with areas shaded underneath to indicate the 50% interval and the width of the density indicates the 95% interval.\n\n\n::: {#fig-non-info-ci .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nmcmc_intervals(fit1$draws(variables = c(\"beta\", \"sigma\")))\nmcmc_areas_ridges(fit1$draws(variables = c(\"beta\", \"sigma\")),\n                  prob_outer = 0.95, prob = 0.5)\n```\n\n::: {.cell-output-display}\n![Interval plots for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-non-info-ci-1.png){#fig-non-info-ci-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Approximate posterior densities for $\\beta$ and $\\sigma$ in a ridgeline plot.](intro_to_stan_files/figure-html/fig-non-info-ci-2.png){#fig-non-info-ci-2 width=672}\n:::\n\nPlots for the 50% Credible Interval (inner band) and 95% Credible Interval (outer band) for $\\beta$ and $\\sigma$. Plots were made using the `bayesplot` package.\n:::\n\n\nOne additional way to check model fit is to assess posterior predictive checks. To do so we draw samples from the posterior predictive distribution $p(y^{new} | y) = \\int p(y^{new} | \\boldsymbol{\\beta}, \\sigma) p(\\boldsymbol{\\beta}, \\sigma | y) d\\boldsymbol{\\beta}d\\sigma$ by first sampling from the posterior (i.e. the draws in the MCMC chains) and then for each set of draws sampling $y^{new}$ given the corresponding values for $x^{new}$. In Stan this is easily accomplished using the generated quantities block. The generated quantities block generates new samples that we define using the current iteration's posterior draws of $\\beta$ and $\\sigma$.\n\n``` stan\ngenerated quantities {\n    // create a vector of N new observations\n    vector[N] y_ppd; \n    \n    // for each observation, sample from the regression likelihod\n    // using the posterior draws\n    for (i in 1:N) {\n        y_ppd[i] = normal_rng(X_c[i,] * beta, sigma);\n    }\n}\n```\n\nWe collect the PPD draws from the fit object using the draws method. From @fig-non-info-ppc we can see that while the predictive densities are centered in the correct location, the variances are far too large.\n\n\n::: {#fig-non-info-ppc .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nlibrary(posterior)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is posterior version 1.5.0\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'posterior'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:bayesplot':\n\n    rhat\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    mad, sd, var\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    %in%, match\n```\n:::\n\n```{.r .cell-code}\nfit1$draws(variables = \"y_ppd\") |> \n    as_draws_df() |>\n    as.matrix() -> y_ppd\n\n\nppc_dens_overlay(ncaaw$W,\n                 y_ppd[1:50, 1:350]) +\n    labs(title = \"Density of PPD Draws of NCAAW Wins\",\n         x = \"Wins\")\n\nppc_intervals(ncaaw$W,\n                 y_ppd[1:50, 1:350],\n                 x = ncaaw$FG3pct) +\n    labs(title = \"Density of PPD Draws of NCAAW Wins by 3pt%\",\n         x = \"3pt%\",\n         y = \"Wins\")\n```\n\n::: {.cell-output-display}\n![PPD densities for the wins given 3pt%.](intro_to_stan_files/figure-html/fig-non-info-ppc-1.png){#fig-non-info-ppc-1 width=672}\n:::\n\n::: {.cell-output-display}\n![PPD intervals for the wins plotted by 3pt%.](intro_to_stan_files/figure-html/fig-non-info-ppc-2.png){#fig-non-info-ppc-2 width=672}\n:::\n\nPosterior Predictive Check plots from `bayesplot`.\n:::\n\n\n### Conjugate Prior Regression Model\n\nNext, we'll implement the regression model with conjugate priors. Conjugacy refers to the situation where the prior and posterior distribution are from the same family. We'll start by re-defining our model.[^1]\n\n[^1]: See wikipedia for more details and derivations: <https://en.wikipedia.org/wiki/Bayesian_linear_regression>\n\n1.  **Conjugate prior:** $p(\\boldsymbol{\\beta}, \\sigma^2) = p(\\boldsymbol{\\beta} | \\sigma^2) p(\\sigma^2)$\n\n    1.  $\\boldsymbol{\\beta} | \\sigma^2 ~ N_2(\\boldsymbol{\\beta}_0, \\sigma^2 \\Lambda_0^{-1})$ where $\\boldsymbol{\\beta}_0 \\in \\mathbb{R}^2$ is a vector of prior coefficients, we'll set it to zero, and $\\Lambda_0$ is a $2\\times2$ prior correlation matrix. We will set $\\Lambda_0 = 10 I_2$ to get a weakly informative prior that is equivalent to ridge regression.\n\n    2.  $\\sigma^2 \\sim InvGamma(\\frac{\\nu_0}{2}, \\frac{1}{2} \\nu_0 s_0^2)$ where $\\nu_0$ is a prior sample size and $s_0$ is the prior standard deviation. We'll set these to $\\nu_0 = 1$ and $s_0^2 = 47$ which is approximately the sample variance of the NCAA women's basketball teams' wins.\n\n    3.  The parameters $\\boldsymbol{\\beta}_0, \\Lambda_0, \\nu_0, s_0^2$ that define the prior are referred to as hyperparameters. We will set them before running the model, although they could also be modeled if we wanted.\n\n2.  **The (Data) Likelihood:** the same as before, $\\mathbf{Y} | \\boldsymbol{\\beta}, \\sigma^2 \\sim N_N(X\\boldsymbol{\\beta}, \\sigma^2 I_N).$\n\n3.  **Posterior:**\n\n    1.  $\\boldsymbol{\\beta} | \\sigma^2, y \\sim N_2(\\boldsymbol{\\beta}_N, \\sigma^2 \\Lambda_N^{-1})$ where $\\boldsymbol{\\beta}_N = \\Lambda_N^{-1}(\\mathbf{X}'\\mathbf{X} \\hat{\\boldsymbol{\\beta}} + \\Lambda_0 \\boldsymbol{\\beta}_0)$ and $\\Lambda_N = (\\mathbf{X}'\\mathbf{X} + \\Lambda_0).$\n    2.  $\\sigma^2 | y) \\sim InvGamma(\\sigma^2 | \\frac{\\nu_0 + N}{2}, \\frac{1}{2} \\nu_0 s_0^2 + \\frac{1}{2}(\\mathbf{y}'\\mathbf{y} + \\boldsymbol{\\beta}_0'\\Lambda_0 \\boldsymbol{\\beta}_0 - \\boldsymbol{\\beta}_N' \\Lambda_N \\boldsymbol{\\beta}_N)).$\n\nWe could again program this model using the analytic posterior. Instead, we'll program it only through the priors and likelihood and let Stan approximate the posterior. I will also allow the model to include more than one predictor so that $\\mathbf{X}$ is a $N \\times (K+1)$ matrix augmented with a column of ones.\n\n``` {.stan filename=\"conjugate-regression.stan\"}\n\n// The input data is a vector 'y' of length 'N'.\ndata {\n  int<lower=0> N;\n  int<lower=0> K;\n  vector[N] y;\n  matrix[N, K] X;\n  \n  // hyperparameters\n  real beta_0;\n  real<lower=0> lambda_0;\n  real<lower=0> nu_0;\n  real<lower=0> s_02;\n}\n\ntransformed data {\n    matrix[N, K+1] X_mat = append_col(rep_vector(1, N), X);\n    vector[K+1] beta_0_vec = rep_vector(beta_0, K+1);\n    matrix[K+1, K+1] Lambda_0 = lambda_0 * identity_matrix(K+1);\n}\n\n// The parameters accepted by the model. Our model\n// accepts two parameters 'mu' and 'sigma'.\nparameters {\n  vector[K+1] beta;\n  real<lower=0> sigma2;\n}\n\n// The model to be estimated. We model the output\n// 'y' to be normally distributed with mean 'mu'\n// and standard deviation 'sigma'.\nmodel {\n  beta ~ multi_normal(beta_0_vec, sigma2 * Lambda_0);\n  sigma2 ~ scaled_inv_chi_square(nu_0, s_02);\n  \n  y ~ normal(X_mat * beta, sqrt(sigma2));\n}\n\ngenerated quantities {\n    real sigma = sqrt(sigma2);\n    vector[N] y_ppd;\n    \n    for (i in 1:N) {\n        y_ppd[i] = normal_rng(X_mat[i,] * beta, sqrt(sigma2));\n    }\n}\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_list2 <- list(\n    N = nrow(ncaaw),\n    K = 1,\n    y = ncaaw$W,\n    X = as.matrix(ncaaw$FG3pct, nrow = nrow(ncaaw)),\n    \n    # hyperparameters\n    beta_0 = 0,\n    lambda_0 = 10,\n    nu_0 = 1,\n    s_02 = 47\n)\n\nfile2 <- file.path(\"conjugate-regression.stan\")\nconj_model <- cmdstan_model(file2)\n\nfit2 <- conj_model$sample(\n    data = data_list2,\n    iter_warmup = 1000,\n    iter_sampling = 1000,\n    thin = 1,\n    refresh = 500,\n    chains = 2,\n    show_messages = TRUE,\n    show_exceptions = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRunning MCMC with 2 sequential chains...\n\nChain 1 Iteration:    1 / 2000 [  0%]  (Warmup) \nChain 1 Iteration:  500 / 2000 [ 25%]  (Warmup) \nChain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup) \nChain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling) \nChain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling) \nChain 1 Iteration: 2000 / 2000 [100%]  (Sampling) \nChain 1 finished in 0.4 seconds.\nChain 2 Iteration:    1 / 2000 [  0%]  (Warmup) \nChain 2 Iteration:  500 / 2000 [ 25%]  (Warmup) \nChain 2 Iteration: 1000 / 2000 [ 50%]  (Warmup) \nChain 2 Iteration: 1001 / 2000 [ 50%]  (Sampling) \nChain 2 Iteration: 1500 / 2000 [ 75%]  (Sampling) \nChain 2 Iteration: 2000 / 2000 [100%]  (Sampling) \nChain 2 finished in 0.3 seconds.\n\nBoth chains finished successfully.\nMean chain execution time: 0.4 seconds.\nTotal execution time: 0.9 seconds.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2$diagnostic_summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$num_divergent\n[1] 0 0\n\n$num_max_treedepth\n[1] 0 0\n\n$ebfmi\n[1] 1.0206289 0.9623406\n```\n:::\n:::\n\n::: {#fig-traceplots-conj .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nlibrary(bayesplot)\n\nmcmc_trace(fit2$draws(variables = c(\"beta\", \"sigma\")))\n\nmcmc_dens_overlay(fit2$draws(variables = c(\"beta\", \"sigma\")))\n```\n\n::: {.cell-output-display}\n![Traceplots for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-traceplots-conj-1.png){#fig-traceplots-conj-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Approximate posterior densities for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-traceplots-conj-2.png){#fig-traceplots-conj-2 width=672}\n:::\n\nDiagnostic plots for the posterior samples. Plots were made using the `bayesplot` package.\n:::\n\n\nAgain the MCMC chains and diagnostics look satisfactory. The summary statistics for the parameters are displayed in @tbl-conj-inf.\n\n\n::: {#tbl-conj-inf .cell tbl-cap='Summary statistics for the posterior samples for $\\beta$ and $\\sigma$.'}\n\n```{.r .cell-code}\nfit2$summary(variables = c(\"beta\", \"sigma\")) |> \n    kableExtra::kbl(booktabs = TRUE, format = \"html\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> variable </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> median </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> mad </th>\n   <th style=\"text-align:right;\"> q5 </th>\n   <th style=\"text-align:right;\"> q95 </th>\n   <th style=\"text-align:right;\"> rhat </th>\n   <th style=\"text-align:right;\"> ess_bulk </th>\n   <th style=\"text-align:right;\"> ess_tail </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> beta[1] </td>\n   <td style=\"text-align:right;\"> -14.4943842 </td>\n   <td style=\"text-align:right;\"> -14.3745500 </td>\n   <td style=\"text-align:right;\"> 3.1037441 </td>\n   <td style=\"text-align:right;\"> 3.1268034 </td>\n   <td style=\"text-align:right;\"> -19.6791600 </td>\n   <td style=\"text-align:right;\"> -9.335630 </td>\n   <td style=\"text-align:right;\"> 1.001786 </td>\n   <td style=\"text-align:right;\"> 584.3318 </td>\n   <td style=\"text-align:right;\"> 684.0491 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> beta[2] </td>\n   <td style=\"text-align:right;\"> 0.9948555 </td>\n   <td style=\"text-align:right;\"> 0.9921695 </td>\n   <td style=\"text-align:right;\"> 0.0997815 </td>\n   <td style=\"text-align:right;\"> 0.1009139 </td>\n   <td style=\"text-align:right;\"> 0.8260818 </td>\n   <td style=\"text-align:right;\"> 1.160146 </td>\n   <td style=\"text-align:right;\"> 1.001759 </td>\n   <td style=\"text-align:right;\"> 579.1196 </td>\n   <td style=\"text-align:right;\"> 649.1763 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> sigma </td>\n   <td style=\"text-align:right;\"> 6.4180363 </td>\n   <td style=\"text-align:right;\"> 6.4040900 </td>\n   <td style=\"text-align:right;\"> 0.2499544 </td>\n   <td style=\"text-align:right;\"> 0.2355036 </td>\n   <td style=\"text-align:right;\"> 6.0326720 </td>\n   <td style=\"text-align:right;\"> 6.856377 </td>\n   <td style=\"text-align:right;\"> 1.004438 </td>\n   <td style=\"text-align:right;\"> 849.0158 </td>\n   <td style=\"text-align:right;\"> 715.7885 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nIn @fig-conj-ci-1 we have the 50% and 95% CIs with the posterior mean displayed as a point. The densities are plotted in ridgelines in @fig-conj-ci-2.\n\n\n::: {#fig-conj-ci .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nmcmc_intervals(fit2$draws(variables = c(\"beta\", \"sigma\")))\nmcmc_areas_ridges(fit2$draws(variables = c(\"beta\", \"sigma\")),\n                  prob_outer = 0.95, prob = 0.5)\n```\n\n::: {.cell-output-display}\n![Interval plots for $\\beta$ and $\\sigma$.](intro_to_stan_files/figure-html/fig-conj-ci-1.png){#fig-conj-ci-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Approximate posterior densities for $\\beta$ and $\\sigma$ in a ridgeline plot.](intro_to_stan_files/figure-html/fig-conj-ci-2.png){#fig-conj-ci-2 width=672}\n:::\n\nPlots for the 50% Credible Interval (inner band) and 95% Credible Interval (outer band) for $\\beta$ and $\\sigma$. Plots were made using the `bayesplot` package.\n:::\n\n\nWe collect the PPD draws from the fit object using the draws method. From @fig-conj-ppc we can see that while the predictive densities match pretty well and the intervals are centered on the OLS line of best fit.\n\n\n::: {#fig-conj-ppc .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\nlibrary(posterior)\n\nfit2$draws(variables = \"y_ppd\") |> \n    as_draws_df() |>\n    as.matrix() -> y_ppd\n\n\nppc_dens_overlay(ncaaw$W,\n                 y_ppd[1:50, 1:350]) +\n    labs(title = \"Density of PPD Draws of NCAAW Wins\",\n         x = \"Wins\")\n\nppc_intervals(ncaaw$W,\n                 y_ppd[1:50, 1:350],\n                 x = ncaaw$FG3pct) +\n    labs(title = \"Density of PPD Draws of NCAAW Wins by 3pt%\",\n         x = \"3pt%\",\n         y = \"Wins\")\n```\n\n::: {.cell-output-display}\n![PPD densities for the wins given 3pt%.](intro_to_stan_files/figure-html/fig-conj-ppc-1.png){#fig-conj-ppc-1 width=672}\n:::\n\n::: {.cell-output-display}\n![PPD intervals for the wins plotted by 3pt%.](intro_to_stan_files/figure-html/fig-conj-ppc-2.png){#fig-conj-ppc-2 width=672}\n:::\n\nPosterior Predictive Check plots from `bayesplot`.\n:::\n\n\n### Bonus: Regression Modeling with Incomplete Data\n\nAs a bonus section, we'll use the `brms` package to fit a regression model where we have incomplete predictor observations. Incomplete data analysis ranges from complete case analysis (incomplete cases are dropped) and mean imputation to multiple imputation, joint modeling, and EM algorithm [@schafer2002].[^2] We're going to use `mice` [@buuren2010mice] and `brms` [@bürkner2018] to demonstrate the imputation and fitting Bayesian regression models with a convenient front-end that writes the Stan code for us.\n\n[^2]: See [@rubin1976, @dempster1977, @rubin1987, @harel2007multiple, @white2011] for more details on incomplete data analysis.\n\nIn our case, we are going to use junior year scoring (points per game) to predict senior year scoring for women's college basketball players from 2020-21 to the 2022-23 seasons. The data set only contains players who played in at least 75% of games each season, so partial seasons due to injury or being a bench player are excluded. Players who only have a junior season are excluded from the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncaaw_i <- read.csv(\"Data/ncaaw-individuals.csv\", header = TRUE)\nhead(ncaaw_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Name Pos_jr Pos_sr G_jr G_sr PPG_jr PPG_sr Cl_jr\n1     A'Jah Davis      F      F   29   32   16.6   16.2   Jr.\n2 Abby Brockmeyer      F      F   NA   31     NA   16.3   Jr.\n3       Abby Feit      F      F   29   28   15.1   15.5   Jr.\n4     Abby Meyers      G      G   NA   30     NA   17.9   Jr.\n5     Abby Meyers      G      G   NA   35     NA   14.3   Jr.\n6   Adriana Shipp      G      G   NA   30     NA   13.9   Jr.\n```\n:::\n:::\n\n\nOur imputation model will be univariate linear regression that use all other variables as predictors. For example, imputing $PPG_{jr}$ will be done by regressing on $PPG_{sr}, G_{jr}, G_{sr}$. $PPG_{jr}$ and $G_{jr}$ are incomplete for $n_{mis} = 176$ players while $n_{obs} = 98$ players have stats from both years. This missing data pattern is displayed in @fig-miss-patt.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mice)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'mice'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    cbind, rbind\n```\n:::\n\n```{.r .cell-code}\nm_pat <- md.pattern(ncaaw_i, plot = TRUE)\n```\n\n::: {.cell-output-display}\n![Missing data patterns for the NCAA women's basketball players from 2020-2023 who played in their junior and senior year. The red boxes correspond to missing values, so there are 176 players who recorded full senior seasons (played in >75% of total games) but missing or shortened junior seasons.](intro_to_stan_files/figure-html/fig-miss-patt-1.png){#fig-miss-patt width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ncaaw_i, aes(PPG_jr, PPG_sr, color = G_jr)) +\n    geom_point() +\n    scale_color_viridis_c(name = \"G - Jr\") +\n    labs(x = \"PPG - Jr\",\n         y = \"PPG - Sr\") +\n    theme_bw()\n```\n\n::: {.cell-output-display}\n![Points per game (PPG) from Junior and Senior seasons.](intro_to_stan_files/figure-html/fig-ppg-jr-sr-1.png){#fig-ppg-jr-sr width=672}\n:::\n:::\n\n\n#### Multiple Imputation with mice\n\nFirst, we'll try out imputing before model fitting using `mice`. MICE stands for Multiple Imputation by Chained Equations and is procedure that creates a set of $M$ completed data sets from an incomplete data set. Multiple Imputation is a three stage procedure:\n\n1.  Each incomplete variable is imputed with posterior predictive draws from a regression model with all other variables as predictors. The procedure iterates through the incomplete variables several times to converge to the posterior predictive distribution of the missing data given the observed.\n2.  These completed data sets are then analyzed individually with a standard complete data method.\n3.  Results from each analysis are combined. Typically this is done with Rubin's rules [@rubin1987], but `brms` follows the advice of @zhou2010 and simply stacks the posterior draw matrices from each fitted model.\n\n\n::: {.cell hash='intro_to_stan_cache/html/mice-fit_cd0c1e64fde4ef6115ea376721a23ce7'}\n\n```{.r .cell-code}\nlibrary(brms)\n\nimps <- mice(ncaaw_i, m = 10, method = \"norm\", maxit = 10, printFlag = FALSE)\n\nfit_brm_mice <- brm_multiple(PPG_sr ~ G_jr * PPG_jr, data = imps, chains = 2,\n                             refresh = 0)\nsummary(fit_brm_mice)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: PPG_sr ~ G_jr * PPG_jr \n   Data: imps (Number of observations: 274) \n  Draws: 20 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 20000\n\nPopulation-Level Effects: \n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      17.86      4.82     8.80    27.62 1.14       94      281\nG_jr           -0.25      0.19    -0.65     0.11 1.17       80      206\nPPG_jr         -0.10      0.29    -0.69     0.43 1.18       75      232\nG_jr:PPG_jr     0.02      0.01    -0.01     0.04 1.21       67      170\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.21      0.10     2.02     2.41 1.04      396     3350\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brms::conditional_effects(fit_brm_mice, \"PPG_jr:G_jr\", resp = \"PPGsr\")) +\n    coord_cartesian(xlim = c(15, 30))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNULL\n```\n:::\n\n::: {.cell-output-display}\n![The estimated conditional effects of PPG as a junior and junior-year Games played on PPG as a senior.](intro_to_stan_files/figure-html/fig-mice-cond-eff-1.png){#fig-mice-cond-eff width=672}\n:::\n:::\n\n\n#### Imputation During Model Fitting\n\nImputation during model fitting takes a different approach. Imputations are made for each incomplete variable using a different conditional model for each variable. This approach differs from MI and MICE in two key ways: (i) the model is only fit once since the imputation model is part of the analysis model, (ii) the model must be constructed uniquely for each analysis scenario whereas MI completed data sets can be re-used with different analyses.\n\n\n::: {.cell hash='intro_to_stan_cache/html/brm-mi-fit_3fd542b4118354f74a2337e178502fa8'}\n\n```{.r .cell-code}\nbform <- bf(PPG_sr | mi() ~ mi(G_jr) * mi(PPG_jr)) +\n    bf(PPG_jr | mi() ~ G_sr + PPG_sr) +\n    bf(G_jr | mi() ~ G_sr + PPG_sr) + set_rescor(FALSE)\n\nfit_brm_mi <- brm(bform, data = ncaaw_i, \n                  refresh = 500, iter = 2000, thin = 1,\n                  backend = \"cmdstanr\", \n                  control = list(adapt_delta = 0.8, \n                                 max_depth = 10,\n                                show_exceptions = FALSE),\n                  chains = 2,\n                  cores = 2)\n\nsummary(fit_brm_mi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: MV(gaussian, gaussian, gaussian) \n  Links: mu = identity; sigma = identity\n         mu = identity; sigma = identity\n         mu = identity; sigma = identity \nFormula: PPG_sr | mi() ~ mi(G_jr) * mi(PPG_jr) \n         PPG_jr | mi() ~ G_sr + PPG_sr \n         G_jr | mi() ~ G_sr + PPG_sr \n   Data: ncaaw_i (Number of observations: 274) \n  Draws: 2 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 2000\n\nPopulation-Level Effects: \n                      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nPPGsr_Intercept          15.99      2.27    11.31    20.63 1.00     1214\nPPGjr_Intercept           5.88      2.34     1.29    10.37 1.00     1999\nGjr_Intercept             2.71      6.17    -9.23    14.63 1.00     1356\nPPGjr_G_sr               -0.04      0.07    -0.17     0.09 1.00     2345\nPPGjr_PPG_sr              0.71      0.08     0.55     0.87 1.00     1359\nGjr_G_sr                  0.56      0.18     0.22     0.90 1.00     1549\nGjr_PPG_sr                0.28      0.23    -0.17     0.72 1.00      908\nPPGsr_miG_jr             -0.29      0.09    -0.48    -0.10 1.00     1084\nPPGsr_miPPG_jr           -0.03      0.14    -0.31     0.27 1.00     1083\nPPGsr_miG_jr:miPPG_jr     0.02      0.01     0.01     0.03 1.00     1076\n                      Tail_ESS\nPPGsr_Intercept           1250\nPPGjr_Intercept           1730\nGjr_Intercept             1301\nPPGjr_G_sr                1370\nPPGjr_PPG_sr              1209\nGjr_G_sr                  1431\nGjr_PPG_sr                 951\nPPGsr_miG_jr              1249\nPPGsr_miPPG_jr            1135\nPPGsr_miG_jr:miPPG_jr     1256\n\nFamily Specific Parameters: \n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma_PPGsr     1.86      0.09     1.70     2.05 1.00     2333     1705\nsigma_PPGjr     2.30      0.16     2.02     2.64 1.00      908     1053\nsigma_Gjr       5.33      0.40     4.63     6.19 1.01      482      961\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\n`brms` is built on Stan, so we can also take a look at the traceplots of the samples in @fig-brm-mi-trace.\n\n\n::: {#fig-brm-mi-trace .cell layout-nrow=\"2\"}\n\n```{.r .cell-code}\nplot(fit_brm_mi, variable = c(\"b_PPGsr\", \"bsp_\"), regex = TRUE, ask = FALSE, N = 3)\n```\n\n::: {.cell-output-display}\n![](intro_to_stan_files/figure-html/fig-brm-mi-trace-1.png){#fig-brm-mi-trace-1 width=672}\n:::\n\n::: {.cell-output-display}\n![](intro_to_stan_files/figure-html/fig-brm-mi-trace-2.png){#fig-brm-mi-trace-2 width=672}\n:::\n\nTraceplots of brms analysis model parameters.\n:::\n\n::: {#fig-brm-mi-trace-imp .cell layout-nrow=\"2\"}\n\n```{.r .cell-code}\nplot(fit_brm_mi, variable = c(\"b_PPGjr\", \"b_Gjr\"), regex = TRUE, ask = FALSE, N = 3)\n```\n\n::: {.cell-output-display}\n![$PPG_{jr}$ imputation model parameters](intro_to_stan_files/figure-html/fig-brm-mi-trace-imp-1.png){#fig-brm-mi-trace-imp-1 width=672}\n:::\n\n::: {.cell-output-display}\n![$G_{jr}$ imputation model parameters](intro_to_stan_files/figure-html/fig-brm-mi-trace-imp-2.png){#fig-brm-mi-trace-imp-2 width=672}\n:::\n\nTraceplots of brms imputation model parameters.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brms::conditional_effects(fit_brm_mi, \"PPG_jr:G_jr\", resp = \"PPGsr\"))\n```\n\n::: {.cell-output-display}\n![The estimated conditional effects of PPG as a junior and junior-year Games played on PPG as a senior.](intro_to_stan_files/figure-html/fig-brm-mi-cond-eff-1.png){#fig-brm-mi-cond-eff width=672}\n:::\n:::\n\n\n## Some Other Useful Resources for Stan\n\nFirst, here's the three essential guides for using Stan:\n\n-   [Stan Function Guide](https://mc-stan.org/docs/functions-reference/index.html) - reference for all the built-in functions and distributions as well as guides for writing custom functions and distributions\n\n-   [Stan User's Guide](https://mc-stan.org/docs/stan-users-guide/index.html) - reference for example models, how to build efficient models, and some inference techniques\n\n-   [Stan Reference Manual](https://mc-stan.org/docs/reference-manual/index.html) - reference for programming in Stan with a focus on how the language works\n\nHere are some other useful packages to use for Bayesian data analysis with Stan (or other packages). We used some of these in this tutorial!\n\n-   [brms](https://paul-buerkner.github.io/brms/index.html): Bayesian regression models using Stan\n\n-   [posterior](https://mc-stan.org/posterior/): Useful for working with Stan output\n\n-   [bayesplot](http://mc-stan.org/bayesplot): ggplot2-based plotting functions for MCMC draws designed work well with Stan\n\n-   [loo](http://mc-stan.org/loo): Leave-one-out cross validation for model checking and selection that works with the log-posterior. Works best with `rstanarm` but can work with `cmdstanr` too.\n\nHere's a list of useful resources for debugging issues with divergences, hitting maximum tree-depth, low EBFMI, and understanding diagnostics:\n\n-   [Stan's Guide to Runtime warnings and convergence problems](https://mc-stan.org/misc/warnings.html)\n\n-   [Prior Choices and Selection](https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations)\n\n-   [Convergence Diagnostics for MCMC](https://arxiv.org/pdf/1909.11827.pdf)\n\n-   [Official Stan Forum](https://discourse.mc-stan.org/)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}